name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: jonlimpw # name of Docker Hub ID
      IMAGE_NAME: dvwadd

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Specify the PHP version you need

    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}
        registry: docker.io
        tag: noagent
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
